import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.tarefasContainer}> 
        <div className={styles.tarefasContent}>       
          <h1>Tarefas</h1>
          <textarea className={styles.textarea}>Digite sua Tarefa ...</textarea>
          <input type="checkbox" placeholder='deixar tarefa publica'/>
          <button className={styles.button}>Registrar</button>
        </div>
      </main>
    </>
  )
}
